
version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: Configure Infrastructure Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
