version: 2.1

jobs:
  # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.16
    steps:
      - checkout
      - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["7f:26:e8:62:0f:d1:37:d2:88:ce:28:06:91:d5:68:29"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure